apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:  
        spp: mongo
    spec: 
      containers:
        - images: mongo
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: mongo
              name: mongo-volume
      volumeMounts:  
        - name: mongo-volume
          hostPath:
            path: mongo  
